added revrisk multilingual and updated readme
wikimedia/liftwing-python pull request #16
Opened 2024-06-13 21:07 UTC by mercelisvaughan

Add ability to make request to revert risk multilingual with validation with updated README

# get prediction

```
model = RevertRiskMultilingualModel()
payload = {
    "lang": "en",
    "rev_id": 123456
}
result = model.request(payload=payload)
print(result)

```

<details>

<summary>Response</summary>

```
{'model_name': 'revertrisk-language-agnostic', 'model_version': '3', 'wiki_db': 'enwiki', 'revision_id': 123456, 'output': {'prediction': False, 'probabilities': {'true': 0.25512129068374634, 'false': 0.7448787093162537}}}
{'model_name': 'revertrisk-multilingual', 'model_version': '4', 'wiki_db': 'enwiki', 'revision_id': 123456, 'output': {'prediction': False, 'probabilities': {'true': 0.3156708782344262, 'false': 0.6843291217655738}}}
```

</details>

2024-06-14 07:40 UTC, isaranto requested changes

2024-06-14 07:40 UTC, isaranto commented on liftwing/models/revertrisk_multilingual.py
> +        return response.json()
This is not needed as the request function of the parent class `LiftwingModel` would do the job.
```suggestion
```

2024-06-14 07:43 UTC, isaranto commented
The CI changes will also need to be fixed. For more information on what to fix check out the [output of the GH action](https://github.com/wikimedia/liftwing-python/actions/runs/9506801086/job/26204843986?pr=16).
To run pre-commit locally you can run:

```
pip install pre-commit
pre-commit run --all-files
```

2024-06-14 10:03 UTC, isaranto commented
@mercelisvaughan in order to be able to import the model with `from liftwing import RevertRiskMultilingualModel` we'll need to add it to the __ini__.py file like we did for the other models.

2024-07-03 06:10 UTC, kevinbazira reviewed
Most of it looks good, besides `liftwing/models/readability.py` which seems redundant.

2024-07-03 06:10 UTC, kevinbazira commented on liftwing/models/readability.py
This file is adding the readability model without ModelMetadata. The readability model has already been added in #11 with ModelMetadata.

2024-07-03 10:16 UTC, isaranto commented on liftwing/models/readability.py
You're right I missed this one!

2024-07-04 06:08 UTC, kevinbazira approved these changes
LGTM!

2024-07-04 06:29 UTC, isaranto approved these changes

2024-07-04 06:30 UTC, merged